### ISSUE TITLE
unable to find "WebServer.h" library

### ISSUE THREAD

**Issue by umeshwalkar** [GerLech/ATSmartHome#1]
Hey GerLech,

Greetings of the day!!!

I was trying to compile the ATSmartHome program it failed to compile.
i did not find "WebServer.h" library anywhere.
can you please guide me

**Comment by GerLech** [comment]
The library is here
https://github.com/espressif/arduino-esp32/blob/master/libraries/WebServer/src/WebServer.h

But if the ESP32 package was installed correct, the library should already be in your environment. You should use ESP32 DevModule as Board.

**Comment by umeshwalkar** [comment]
Thanks for replying.

i am trying "SmartHomeV2_8266.ino" example with ESP8266 node mcu v1.0 board(ESP-12E).

error received as following

In file included from C:\Users\PC\AppData\Local\Temp\arduino_build_926386\sketch\AT_Webserver.cpp:11:0:

AT_Webserver.h:32:23: error: WebServer.h: No such file or directory

 #include <WebServer.h>

**Comment by GerLech** [comment]
The current and future versions of the library no longer supports ESP8266 since I had problems with the RAM size. I mentioned this in the readMe file too and I removed the example code for the ESP8266
